server:
  port: 9000
spring:
  application:
    name: admin-dashboard
  admin:
    instance-auth:
      enabled: false
    # Add this to handle duplicate instances
    instance-proxy:
      ignore-hostname: true
    # Optional: Set instance resolver to use consistent naming
    instance-resolver: service-instance
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/