server:
  port: 8081

spring:
  application:
    name: service-1
  boot:
    admin:
      client:
        url: http://localhost:9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    appname: ${spring.application.name}  # explicitly set Eureka app name
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka