server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
management:
  endpoints:
    web:
      exposure:
        include: "*"